### PR TITLE
Add CKEditor init and styles

### PR DESCRIPTION
**Pull request by tokland**
Closes https://github.com/EyeSeeTea/dhis2-core/issues/19

### CODE REVIEW

**Review by adrianq — CHANGES_REQUESTED** [review]
@tokland I am adding my review in this repo but I guess some changes may have to go to d2-analysis. Anyway, they are all functional/cosmetics details:
- [ ] Remove background-color from cke_dialog_background_cover
- [ ] Emoticons dialog has a larger bottom margin than top margin. I think it is a bit tricky to solve as it has to do with the height from what I saw in the css but just in case it is not too tricky to solve
- [ ] As we are not gonna have the dark background color for the modal it would be great if we can show the emoticons button as pressed while the emoticons dialog is open. Same effect it is used when clicking the button should be fine.
- [ ] Actually, at the moment we show a rectangle around the button is selected (for instance bold or italic). Maybe it is better and more clear for the user if we show it with the same styles we have while pressing the button.
- [ ] When creating a new interpretation, I have seen at least two situations where the emoticons dialog is not hidden: when clicking on the exit (x) button and when clicking inside the textarea. It is actually hidden when we click in the textarea if we are posting a comment. In case it helps.

**Comment by adrianq** [comment]
Not sure if this can be of any help, I know that I already told you but just in case: https://github.com/EyeSeeTea/d2-analysis/blob/mentions/src/ui/MentionToolbar.js#L82-L89

**Comment by tokland** [comment]
Review comments do not appear on waffle, I'll copy adrianq's requests here:

- [x] Remove background-color from cke_dialog_background_cover **(with opacity: 0)**
- [x] Emoticons dialog has a larger bottom margin than top margin. I think it is a bit tricky to solve as it has to do with the height from what I saw in the css but just in case it is not too tricky to solve **(finally that was easy, just remove the forced height)**
- [x] As we are not gonna have the dark background color for the modal it would be great if we can show the emoticons button as pressed while the emoticons dialog is open. Same effect it is used when clicking the button should be fine.
- [x] Actually, at the moment we show a rectangle around the button is selected (for instance bold or italic). Maybe it is better and more clear for the user if we show it with the same styles we have while pressing the button.
- [x] When creating a new interpretation, I have seen at least two situations where the emoticons dialog is not hidden: when clicking on the exit (x) button and when clicking inside the textarea. It is actually hidden when we click in the textarea if we are posting a comment. In case it helps (the different behaviour was because of z-index on the modal; now they should behave the same way)

**Comment by tokland** [comment]
Just to be sure, we are removing any overlay shadowing, aren't we? I am confused by the reference to the `hasDestroyOnBlurHandlerGlobal`snippet.

**Comment by tokland** [comment]
Testing screencastify:

https://drive.google.com/file/d/1o2U2mFzljECKlwdkYqVCt6kIrI464RKk/view

**Review by adrianq — APPROVED** [review]

**Pull request closed without merging**
