### PR TITLE
Feature/interpretations improvements

### PR DESCRIPTION
**Pull request by tokland**

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland Let me know if this is ready to be merged... Anyway, I had a quick look to the PR and I think we should be consistent with [this other PR](https://github.com/EyeSeeTea/dhis2-pivot/pull/6/files) and translate at least the same languages.

**Comment by tokland** [comment]
Ok, will do (in this package, I only found translations related to interpretations for English, so I thought it wasn't needed)

**Review by adrianq — CHANGES_REQUESTED** [review]
@tokland As discussed, can you remove other languages? I already asked for isAdminInit in [d2-analysis PR](https://github.com/EyeSeeTea/d2-analysis/pull/11) so I will wait for your answer...

**Comment by tokland** [comment]
Revert done

**Review by adrianq — APPROVED** [review]

**Pull request merged**
